### ISSUE TITLE
avconv comamnd line Error: [image2pipe @ 0000000000308580] Could not find codec parameters (Video: mjpeg)

### ISSUE THREAD

**Issue by JasonHXiang** [softkot/adbcap#1]
I has install avconv on my Windows 7 system. According to README.md, the command line below occured an codec parameter **ERROR**
`avconv -y -f image2pipe -r 2 -vcodec mjpeg -i stream.jpgs -r 10 video.mp4`

Have you everyone run into this situation? Please help me out, thanks!

**Comment by softkot** [comment]
You should post this issue to avconv developers.
